#Grab the latest alpine image
FROM caubequay00/centos-ops
USER 0
RUN rm -f /headless/.vnc/passwd 
RUN rm -f /headless/.config/bg_*.png
RUN rm -f /headless/Desktop/*
ADD chromium-browser.desktop /headless/Desktop
ADD firefox.desktop /headless/Desktop
USER 1000
#ENV VNC_PW=mypassword
# Run the image as a non-root user
#RUN adduser -D myuseri

# Run the app.  CMD is required to run on Heroku
# $PORT is set by Heroku			

